version: '3'

volumes:
  h2_data:
    driver: local
  caddy_data:
    driver: local

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    volumes:
      - h2_data:/opt/keycloak/data
      #- ${PWD}/target/scim-for-keycloak-kc-20-b1.jar:/opt/keycloak/providers/scim-for-keycloak-kc-20-b1.jar
      - ${PWD}/target/scim-for-keycloak-bundle-kc-20-b1/commons-io-commons-io-2.11.0.jar:/opt/keycloak/providers/commons-io-commons-io-2.11.0.jar
      - ${PWD}/target/scim-for-keycloak-bundle-kc-20-b1/org.abego.treelayout-org.abego.treelayout.core-1.0.3.jar:/opt/keycloak/providers/org.abego.treelayout-org.abego.treelayout.core-1.0.3.jar
      - ${PWD}/target/scim-for-keycloak-bundle-kc-20-b1/org.apache.commons-commons-lang3-3.12.0.jar:/opt/keycloak/providers/org.apache.commons-commons-lang3-3.12.0.jar
      - ${PWD}/target/scim-for-keycloak-bundle-kc-20-b1/de.captaingoldfish-scim-for-keycloak-resources-kc-20-b1.jar:/opt/keycloak/providers/de.captaingoldfish-scim-for-keycloak-resources-kc-20-b1.jar
      - ${PWD}/target/scim-for-keycloak-bundle-kc-20-b1/de.captaingoldfish-scim-for-keycloak-server-kc-20-b1.jar:/opt/keycloak/providers/de.captaingoldfish-scim-for-keycloak-server-kc-20-b1.jar
      - ${PWD}/target/scim-for-keycloak-bundle-kc-20-b1/org.antlr-antlr4-4.10.1.jar:/opt/keycloak/providers/org.antlr-antlr4-4.10.1.jar
      - ${PWD}/target/scim-for-keycloak-bundle-kc-20-b1/org.glassfish-javax.json-1.0.4.jar:/opt/keycloak/providers/org.glassfish-javax.json-1.0.4.jar
      - ${PWD}/target/scim-for-keycloak-bundle-kc-20-b1/de.captaingoldfish-scim-sdk-common-1.17.1-kc-SNAPSHOT.jar:/opt/keycloak/providers/de.captaingoldfish-scim-sdk-common-1.17.1-kc-SNAPSHOT.jar
      - ${PWD}/target/scim-for-keycloak-bundle-kc-20-b1/org.antlr-antlr4-runtime-4.10.1.jar:/opt/keycloak/providers/org.antlr-antlr4-runtime-4.10.1.jar
      - ${PWD}/target/scim-for-keycloak-bundle-kc-20-b1/org.slf4j-slf4j-api-2.0.7.jar:/opt/keycloak/providers/org.slf4j-slf4j-api-2.0.7.jar
      - ${PWD}/target/scim-for-keycloak-bundle-kc-20-b1/de.captaingoldfish-scim-sdk-server-1.17.1-kc-SNAPSHOT.jar:/opt/keycloak/providers/de.captaingoldfish-scim-sdk-server-1.17.1-kc-SNAPSHOT.jar
      #- ${PWD}/target/scim-for-keycloak-bundle-kc-20-b1/org.antlr-antlr-runtime-3.5.3.jar:/opt/keycloak/providers/org.antlr-antlr-runtime-3.5.3.jar
      - ${PWD}/target/scim-for-keycloak-bundle-kc-20-b1/org.antlr-ST4-4.3.2.jar:/opt/keycloak/providers/org.antlr-ST4-4.3.2.jar
    environment:
      KC_HTTP_RELATIVE_PATH: /auth
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: 'true'
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_PROXY: 'edge'
      KC_LOG_LEVEL: INFO
    ports:
      - 8080:8080
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
  caddy:
    image: caddy:2.4.6-alpine
    restart: unless-stopped
    command: caddy reverse-proxy --from https://s01.villamiramar.fr:443 --to http://keycloak:8080
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
    depends_on:
      - keycloak
